server:
  port: 8082

spring:
  application:
    name: spring-boot-sms

#--------阿里云短信配置参数 start--------------#
aliyun:
  sms:
    #阿里云 accessKeyId（安全信息管理下面）
    accessKeyId:
    #阿里云 accessKeySecret（安全信息管理下面）
    accessKeySecret:
    #产品名称:云通信短信API产品,开发者无需替换
    product: Dysmsapi
    #产品域名,开发者无需替换
    domain: dysmsapi.aliyuncs.com
    #产品地区,开发者无需替换
    regionId: cn-hangzhou
    #短信签名名称（国内/国际/港澳台消息-签名管理下面）
    signName: ABCD商城
    #发送日期 支持30天内记录查询，格式yyyyMMdd
    dateFormat: yyyyMMdd
    #服务结点
    endpointName: cn-hangzhou
#--------阿里云短信配置参数 end--------------#





